export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS'
export const CHANGE_USERINFO = 'CHANGE_USERINFO'
export const CHANGE_MYGOODS = 'CHANGE_MYGOODS'
export const CHANGE_MYPURCHASES = 'CHANGE_MYPURCHASES'
